<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <?php require APP_DIR . 'views/common/head.phtml'; ?>
    </head>
    <body>
        <div id="mainWrapper">
            <div id="headerWrapper">
                <?php require APP_DIR . 'views/common/header.phtml'; ?>
            </div>
            <div class="clearBoth"></div>
            <div id="contentWrapper">
                <div id="leftSideBar">
                    <?php require APP_DIR . 'views/common/leftSideBar.phtml'; ?>
                </div>
                <div id="content">
                    <?php require $contentPartial; ?>
                </div>
                <div id="rightSideBar">
                    <?php require APP_DIR . 'views/common/rightSideBar.phtml'; ?>
                </div>
            </div>
            <div class="clearBoth"><hr/></div>
            <div id="footerWrapper">
                <?php require APP_DIR . 'views/common/footer.phtml'; ?>
            </div>
        </div>
        <script type="text/javascript" src="js/jquery.js"></script>
        <script type="text/javascript" src="js/script.js"></script>
    </body>
</html>