<div class="contentBox">
    <h1 class="contentBoxHeadText">Nouveautes</h1>
    <div class="contentBoxContent">
        <?php for ($i = 1; $i <= 10; $i++): ?>
            <div class="articleCatalog">
                <a href="./">
                    <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        <?php endfor; ?>
            <div class="clearBoth"></div>
        </div>
    </div>
    <div class="contentBox">
    <h1 class="contentBoxHeadText">Vetements</h1>
        <div class="contentBoxContent">
        <?php for ($i = 1; $i <= 6; $i++): ?>
                <div class="articleCatalog">
                    <a href="./">
                        <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                        <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                        <h1 class="productMediumName">Jackette hiver</h1>
                    </a>
                </div>
        <?php endfor; ?>
        <div class="clearBoth"></div>
    </div>
</div>
