
<div class="contentBox">
    <h1 class="contentBoxHeadText">Nouveautes</h1>
    <div class="contentBoxContent">
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="clearBoth"></div>
    </div>
</div>
<div class="contentBox">
    <h1 class="contentBoxHeadText">Vetements</h1>
    <div class="contentBoxContent">
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="articleCatalog">
            <a href="./">
                <img class="productMediumImage" src="styles/default/images/medium_product.jpg" alt=""/>
                <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                <h1 class="productMediumName">Jackette hiver</h1>
            </a>
        </div>
        <div class="clearBoth"></div>
    </div>
</div>