<img id="logoImage" src="styles/default/images/logo.jpg" alt="Company Logo"/>
<div id="countryControl">
    <ul>
        <li><strong>Pays</strong>:</li>
        <li><a href="#"><img src="styles/default/images/flags/uk.gif" alt=""/></a></li>
        <li><a href="#"><img src="styles/default/images/flags/ro.gif" alt=""/></a></li>
        <li><a href="#"><img src="styles/default/images/flags/bg.gif" alt=""/></a></li>
        <li><a href="#"><img src="styles/default/images/flags/us.gif" alt=""/></a></li>
    </ul>
</div>
<div class="clearBoth"></div>
<div id="menuBar">
    <ul>
        <li><a href="./">Accueil</a></li>
        <li><a href="./">Nouveautes</a></li>
        <li><a href="./">Meilleures Ventes</a></li>
        <li><a href="./">Menu item</a></li>
    </ul>
</div>
<div class="clearBoth"></div>
<hr/>