<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="keywords" content="<?php
if (isset($keywords)) {
    echo $keywords;
} else {
    echo APP_KEYWORDS;
}
?>" />
<meta name="description" content="<?php
      if (isset($description)) {
          echo $description;
      } else {
          echo APP_DESCRIPTION;
      }
?>" />
<meta name="author" content="Vilherbal"/>
<title><?php
      if (isset($title)) {
          echo $title;
      } else {
          echo(APP_NAME);
      }
?></title>
<link rel="icon" type="image/gif" href="styles/default/images/cart_icon.gif"/>
<link rel="stylesheet" type="text/css" href="styles/default/style.css" />