<div class="sideBox">
    <h1 class="boxHead">Categories</h1>
    <div class="boxContent">
        <ul class="categories">
            <li><a href="./">Vetements</a></li>
            <li><a href="./">Voitures</a></li>
            <li><a href="./">Ordinateurs<strong>&nbsp;&gt;</strong></a></li>
            <li><a href="./">Claviers</a></li>
            <li><a href="./">Ecrans</a></li>
            <li><a href="./">Articles</a></li>
            <li><a href="./">Nimporte</a></li>
            <li><a href="./">Rien</a></li>
        </ul>
    </div>
</div>
<div class="sideBox">
    <h1 class="boxHead">Voir Aussi</h1>
    <div class="boxContent">
        <div class="articleSideCatalog">
            <a href="./"><img class="productSmallImage" src="styles/default/images/small_product.jpg" alt=""/></a>
            <div class="productSideDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleSideCatalog">
            <a href="./"><img class="productSmallImage" src="styles/default/images/small_product.jpg" alt=""/></a>
            <div class="productSideDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleSideCatalog">
            <a href="./"><img class="productSmallImage" src="styles/default/images/small_product.jpg" alt=""/></a>
            <div class="productSideDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleSideCatalog">
            <a href="./"><img class="productSmallImage" src="styles/default/images/small_product.jpg" alt=""/></a>
            <div class="productSideDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleSideCatalog">
            <a href="./"><img class="productSmallImage" src="styles/default/images/small_product.jpg" alt=""/></a>
            <div class="productSideDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleSideCatalog">
            <a href="./"><img class="productSmallImage" src="styles/default/images/small_product.jpg" alt=""/></a>
            <div class="productSideDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleSideCatalog">
            <a href="./"><img class="productSmallImage" src="styles/default/images/small_product.jpg" alt=""/></a>
            <div class="productSideDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="sideBox">
    <h1 class="boxHead">Meilleures Ventes</h1>
    <div class="boxContent">
        <div class="articleTopCatalog">
            <a href="./"><img class="productTopImage" src="styles/default/images/top_product.jpg" alt=""/></a>
            <div class="productTopDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleTopCatalog">
            <a href="./"><img class="productTopImage" src="styles/default/images/top_product.jpg" alt=""/></a>
            <div class="productTopDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleTopCatalog">
            <a href="./"><img class="productTopImage" src="styles/default/images/top_product.jpg" alt=""/></a>
            <div class="productTopDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
        <div class="articleTopCatalog">
            <a href="./"><img class="productTopImage" src="styles/default/images/top_product.jpg" alt=""/></a>
            <div class="productTopDetails">
                <a href="./">
                    <h1 class="productMediumPrice">Price: <span class="productPriceValue">623&euro;</span></h1>
                    <h1 class="productMediumName">Jackette hiver</h1>
                </a>
            </div>
        </div>
    </div>
</div>