<div class="sideBox">
    <h1 class="boxHead">Liens Magasin</h1>
    <div class="boxContent">
        <?php require APP_DIR . 'views/common/userLinks.phtml'; ?>
    </div>
</div>
<div class="sideBox">
    <h1 class="boxHead">Recherche</h1>
    <div class="boxContent">
        <form action="./" method="get">
            <div>
                <input type="text" value=""/>
                <input type="image" src="styles/default/images/search_button.jpg" value="Recherche"/>
            </div>
        </form>
    </div>
</div>
<div class="sideBox">
    <h1 class="boxHead">Convertisseur</h1>
    <div class="boxContent">
        <select>
            <option>Euro</option>
            <option>Pounds</option>
            <option>US Dollar</option>
            <option>CA Dollar</option>
            <option>AU Dollar</option>
        </select>
    </div>
</div>