<ul>
    <li><a href="#"><img src="styles/default/images/cart_icon.gif" alt="Panier"/></a><a href="#">Mon panier</a></li>
    <?php
    if (!isset($_SESSION['user_id'])): ?>
        <li><a id="connectionSideLink" href="?controller=users&amp;action=login">Se connecter</a></li>
        <div id="loginSideForm" class="loginForm">
            <form action="?controller=users&amp;action=login" method="post">
                <input type="text" name="username" value="Nom d'utilisateur"/>
                <input type="text" name="password" value="Mot de passe"/>
                <input type="submit" name ="login" value="Se connecter"/>
            </form>
        </div>
    <?php else: ?>
            <li><a href="?controller=users&amp;action=logout">Se deconecter</a></li>
    <?php endif; ?>
</ul>